In [3]:
import pandas as pd
import requests

In [6]:
response = requests.get('https://api.themoviedb.org/3/movie/top_rated?api_key=4ecc8dca976766083c68aae9e3e98ee6&language=en-US&page=1')

In [13]:
df =pd.DataFrame(response.json() ['results'])[['id','title','overview', 'release_date', 'popularity', 'vote_average', 'vote_count']]

In [14]:
df

,id,title,overview,release_date,popularity,vote_average,vote_count
0,19404,Dilwale Dulhania Le Jayenge,"Raj is a rich, carefree, happy-go-lucky second...",1995-10-20,24.685,8.7,3176
1,278,The Shawshank Redemption,Framed in the 1940s for the double murder of h...,1994-09-23,59.167,8.7,19865
2,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",1972-03-14,61.777,8.7,14906
3,724089,Gabriel's Inferno Part II,Professor Gabriel Emerson finally learns the t...,2020-07-31,9.414,8.7,1313
4,283566,Evangelion: 3.0+1.0 Thrice Upon a Time,"In the aftermath of the Fourth Impact, strande...",2021-03-08,166.556,8.7,336
5,761053,Gabriel's Inferno Part III,The final part of the film adaption of the ero...,2020-11-19,23.082,8.6,881
6,696374,Gabriel's Inferno,An intriguing and sinful exploration of seduct...,2020-05-29,8.971,8.6,2126
7,424,Schindler's List,The true story of how businessman Oskar Schind...,1993-11-30,43.552,8.6,11908
8,240,The Godfather: Part II,In the continuing saga of the Corleone crime f...,1974-12-20,37.738,8.6,8956
9,372058,Your Name.,High schoolers Mitsuha and Taki are complete s...,2016-08-26,127.131,8.6,7951
10,255709,Hope,After 8-year-old So-won narrowly survives a br...,2013-10-02,7.623,8.6,220
11,632632,Given,The film centers on the love relationship amon...,2020-08-22,114.744,8.6,258
12,129,Spirited Away,"A young girl, Chihiro, becomes trapped in a st...",2001-07-20,65.781,8.5,11919
13,496243,Parasite,"All unemployed, Ki-taek's family takes peculia...",2019-05-30,97.427,8.5,12291
14,441130,Wolfwalkers,"In a time of superstition and magic, when wolv...",2020-10-26,18.988,8.5,579
15,497,The Green Mile,A supernatural tale set on death row in a Sout...,1999-12-10,56.330,8.5,12890
16,526702,Black Beauty,"Born free in the American West, Black Beauty i...",2020-11-27,14.972,8.5,222
17,389,12 Angry Men,The defense and the prosecution have rested an...,1957-04-10,23.944,8.5,5892
18,592350,My Hero Academia: Heroes Rising,Class 1-A visits Nabu Island where they finall...,2019-12-20,323.094,8.5,806
19,680,Pulp Fiction,"A burger-loving hit man, his philosophical par...",1994-09-10,78.476,8.5,21900

In [16]:
for i in range(1,461):
    response = requests.get('https://api.themoviedb.org/3/movie/top_rated?api_key=4ecc8dca976766083c68aae9e3e98ee6&language=en-US&page={}'.format(i))
    temp_df =pd.DataFrame(response.json() ['results'])[['id','title','overview', 'release_date', 'popularity', 'vote_average', 'vote_count']]
    df = df.append(temp_df, ignore_index = True)

In [18]:
df.shape

(9220, 7)

In [20]:
df.to_csv('movies.csv')